import React, { Component } from 'react';

export class ProgammingBody extends Component {
  render() {
    return (
      <div>
              <div className="body-container">
		<div className='purple center-title'>Programming Submissions <br/>and Suggestions</div>
    

<div className="left"><section className="link-border">
Penguicon's programming is, by and large, generated by our community. Your ideas, suggestions, and general brainstorming capabilities are combed through by our programming team (via this form) to generate a comprehensive and diverse weekend of so much awesome no one person can experience it all.  <br />
If you have an idea for an event, panel, birds of a feather, or gaming event then fill out this form and let us know.  You don't have to run an event to suggest one, but suggesting one or more presenters help our programming staff make the magic happen.<br />

In the interest of full transparency, this year we are publishing the suggestions made by our attendees and whether those suggestions will make it to programming. No identifying information will be given - only whether or not a presenter has been identified. <br />

 If you're planning on presenting 3 or more hours of programming at Penguicon, or if you provide your presentation documents for us to publish to the community,  you will qualify for a discounted badge price.  Panelist that present more than three hours of programming pay $30 for their badge. <br />

Once your idea has been submitted, someone from the programming team will reach out to you.  If you have questions, you can always reach out to <a className="text-link" href={`mailto:programming@penguicon.org`}>programming@penguicon.org</a> or <a className="text-link" href={`mailto:conchair19@penguicon.org`}>conchair19@penguicon.org</a>  <br /></section>
<ul>
Definitions:  
	<li>Birds of a Feather- a meet-up style event without a real agenda or speaker</li>
	<li>Panel- single speaker, multi-speaker, or event about a particular topic presented to an audience without or without participation</li>
	<li>DIY Panel- Hands on event where a craft or skill is being taught</li>
	<li>Food/Drink Panel-Specific type of event with room requirements, equipment needs, and often participation restrictions</li>
	<li>Computer Lab Panel-Specific event that would require participants to have computer access</li>
	<li>Gaming Event- Scheduled Board Game events</li>
	<li>Special event description: Large Event that falls outside of the normal paneling descriptions.  Previous examples include Battle Bots, Geeky Burlesque, and Break-Out Rooms.</li>
</ul>
</div>

      </div>

      </div>
    )
  }
}

export default ProgammingBody
